version: '3.8'

services:
  # PHP Backend Service
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auth_backend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/config:/var/www/config
    environment:
      - DB_HOST=mysql
      - DB_NAME=auth_db
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - JWT_SECRET=abdelhaymalloulifinalproject
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mysql
    networks:
      - auth_network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=auth_db
      - MYSQL_USER=auth_user
      - MYSQL_PASSWORD=auth_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - auth_network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://php:80/api
    depends_on:
      - php
    networks:
      - auth_network

  # phpMyAdmin dashboard for MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: auth_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - mysql
    networks:
      - auth_network

# Volumes
volumes:
  mysql_data:

# Networks
networks:
  auth_network:
    driver: bridge
